# Singleton service factory configuration/IoC injection
singletons:
- com.networknt.configserver.provider.IProvider:
  # - com.networknt.configserver.provider.FileSystemProviderImpl
  # Using mock for JUnit test and comment them out by default.
  # - com.networknt.configserver.provider.GitProviderImpl
  # - com.networknt.configserver.provider.VaultProviderImpl
  - com.networknt.configserver.provider.MongoDBProviderImpl
- com.networknt.server.StartupHookProvider:
  - com.networknt.configserver.db.MongoStartupHook
- com.networknt.server.ShutdownHookProvider:
  - com.networknt.configserver.db.MongoShutdownHook
- com.networknt.registry.URL:
    - com.networknt.registry.URLImpl:
        protocol: light
        host: localhost
        port: 8080
        path: portal
        parameters:
          registryRetryPeriod: '30000'
- com.networknt.portal.registry.client.PortalRegistryClient:
    - com.networknt.portal.registry.client.PortalRegistryClientImpl
- com.networknt.registry.Registry:
    - com.networknt.portal.registry.PortalRegistry
- com.networknt.balance.LoadBalance:
    - com.networknt.balance.RoundRobinLoadBalance
- com.networknt.cluster.Cluster:
    - com.networknt.cluster.LightCluster