# Singleton service factory configuration/IoC injection
singletons:
- com.networknt.configserver.provider.IProvider:
  - com.networknt.configserver.provider.FileSystemProviderImpl
  # Using mock for JUnit test and comment them out by default.
  # - com.networknt.configserver.provider.GitProviderImpl
  # - com.networknt.configserver.provider.VaultProviderImpl
